import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Sidebar from "@/app/components/Sidebar";

import { SidebarContextProvider } from "@/app/context/SidebarContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hoàng Như",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarContextProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <main className="flex h-screen">
            <Sidebar />
            {children}
          </main>
        </body>
      </html>
    </SidebarContextProvider>
  );
}
